//! Swap Plan Types
//!
//! This module defines the intermediate `SwapPlan` structure that bridges
//! Oracle/Features output with direct AMM execution via DirectBuyBuilder.

use serde::{Deserialize, Serialize};
use solana_sdk::pubkey::Pubkey;

/// A swap execution plan generated by strategy/feature modules.
///
/// This structure represents a validated, ready-to-execute swap intent
/// that will be executed via DirectBuyBuilder for direct AMM interaction.
///
/// # Field Sources
///
/// - `authority`: Provided by user configuration (wallet public key)
/// - `pool_amm_id`: Determined by Oracle (which pool to trade)
/// - `amount_in`: Calculated by Features (position sizing based on score and config)
/// - `min_amount_out`: Calculated by Features (slippage protection)
/// - `timeout`: Calculated by Features (execution window)
///
/// # Validation
///
/// Before execution, SwapPlan must satisfy:
/// - `amount_in >= MIN_SWAP_AMOUNT` (1000 lamports)
/// - `min_amount_out > 0`
/// - `timeout` is in the future
/// - `timeout - now <= MAX_TIMEOUT_DURATION` (7 days)
/// - `pool_amm_id` belongs to whitelisted AMM program
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SwapPlan {
    /// Authority that will sign and execute this swap
    ///
    /// This is the user's wallet public key. The same authority must sign
    /// both the `initialize_intent` and `execute_planned_swap` transactions.
    pub authority: Pubkey,

    /// Target AMM pool to execute the swap on
    ///
    /// Must be a pool from a whitelisted AMM program (Pump.fun or Bonk.fun).
    /// The Oracle identifies this from token metadata and pool detection.
    pub pool_amm_id: Pubkey,

    /// Amount of input tokens to swap (in lamports)
    ///
    /// Calculated by Features module based on:
    /// - User's maximum position size configuration
    /// - Oracle score (may scale position with confidence)
    /// - Available liquidity in the pool
    /// - Risk management rules
    ///
    /// Must be >= MIN_SWAP_AMOUNT (1000 lamports)
    pub amount_in: u64,

    /// Minimum acceptable output amount (in token base units)
    ///
    /// Provides slippage protection. Calculated by Features module based on:
    /// - Expected output from current pool price
    /// - User's maximum slippage tolerance
    /// - Market volatility considerations
    ///
    /// Must be > 0
    pub min_amount_out: u64,

    /// Unix timestamp when this intent expires
    ///
    /// Calculated as current_time + execution_window (from strategy config).
    /// After this time, the intent cannot be executed.
    ///
    /// Must be:
    /// - In the future (> current_timestamp)
    /// - Within MAX_TIMEOUT_DURATION from now (≤ 7 days)
    pub timeout: i64,

    /// Optional metadata for off-chain tracking and analysis
    ///
    /// Not sent to on-chain program, used for:
    /// - Logging and debugging
    /// - Performance tracking
    /// - Strategy attribution
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata: Option<SwapPlanMetadata>,
}

/// Optional metadata attached to a SwapPlan for tracking
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SwapPlanMetadata {
    /// Oracle score that generated this plan (0-100)
    pub oracle_score: u8,

    /// Strategy that generated this plan
    pub strategy: String,

    /// Expected bonding curve progress (0.0 - 1.0)
    pub bonding_curve_progress: Option<f64>,

    /// Risk level assessment
    pub risk_level: RiskLevel,

    /// Token mint address being purchased
    pub token_mint: Pubkey,

    /// Timestamp when this plan was created
    pub created_at: i64,
}

/// Risk level classification for a swap plan
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
pub enum RiskLevel {
    /// Low risk: High oracle score, good liquidity, low holder concentration
    Low,
    /// Medium risk: Moderate oracle score, acceptable parameters
    Medium,
    /// High risk: Lower oracle score or concerning indicators
    High,
    /// Very high risk: Anomaly detected or extreme parameters
    VeryHigh,
}

impl SwapPlan {
    /// Create a new SwapPlan with required fields
    pub fn new(
        authority: Pubkey,
        pool_amm_id: Pubkey,
        amount_in: u64,
        min_amount_out: u64,
        timeout: i64,
    ) -> Self {
        Self {
            authority,
            pool_amm_id,
            amount_in,
            min_amount_out,
            timeout,
            metadata: None,
        }
    }

    /// Add metadata to this SwapPlan
    pub fn with_metadata(mut self, metadata: SwapPlanMetadata) -> Self {
        self.metadata = Some(metadata);
        self
    }

    /// Check if this plan is expired given a current timestamp
    pub fn is_expired(&self, current_timestamp: i64) -> bool {
        current_timestamp > self.timeout
    }

    /// Get a human-readable description of this swap plan
    pub fn description(&self) -> String {
        format!(
            "Swap {} lamports on pool {} (expires at {})",
            self.amount_in, self.pool_amm_id, self.timeout
        )
    }
}

/// Builder for constructing validated SwapPlans
///
/// Provides a fluent interface for creating SwapPlans with validation.
///
/// # Example
///
/// ```ignore
/// use ghost_core::SwapPlanBuilder;
///
/// let plan = SwapPlanBuilder::new(authority, pool_amm_id)
///     .amount_in(1_000_000)
///     .min_amount_out(900_000)
///     .timeout_seconds(3600)  // 1 hour from now
///     .with_score(85)
///     .with_strategy("snipe_new_pool")
///     .build()?;
/// ```
#[derive(Debug, Clone)]
pub struct SwapPlanBuilder {
    authority: Pubkey,
    pool_amm_id: Pubkey,
    amount_in: Option<u64>,
    min_amount_out: Option<u64>,
    timeout: Option<i64>,
    oracle_score: Option<u8>,
    strategy: Option<String>,
    bonding_curve_progress: Option<f64>,
    risk_level: Option<RiskLevel>,
    token_mint: Option<Pubkey>,
}

impl SwapPlanBuilder {
    /// Create a new builder with required authority and pool
    pub fn new(authority: Pubkey, pool_amm_id: Pubkey) -> Self {
        Self {
            authority,
            pool_amm_id,
            amount_in: None,
            min_amount_out: None,
            timeout: None,
            oracle_score: None,
            strategy: None,
            bonding_curve_progress: None,
            risk_level: None,
            token_mint: None,
        }
    }

    /// Set the input amount
    pub fn amount_in(mut self, amount: u64) -> Self {
        self.amount_in = Some(amount);
        self
    }

    /// Set the minimum output amount
    pub fn min_amount_out(mut self, amount: u64) -> Self {
        self.min_amount_out = Some(amount);
        self
    }

    /// Set the timeout as an absolute Unix timestamp
    pub fn timeout(mut self, timestamp: i64) -> Self {
        self.timeout = Some(timestamp);
        self
    }

    /// Set the timeout relative to now (in seconds)
    pub fn timeout_seconds(mut self, seconds: u64) -> Self {
        use std::time::{SystemTime, UNIX_EPOCH};
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_secs() as i64;
        self.timeout = Some(now + seconds as i64);
        self
    }

    /// Add oracle score to metadata
    pub fn with_score(mut self, score: u8) -> Self {
        self.oracle_score = Some(score);
        self
    }

    /// Add strategy name to metadata
    pub fn with_strategy(mut self, strategy: impl Into<String>) -> Self {
        self.strategy = Some(strategy.into());
        self
    }

    /// Add bonding curve progress to metadata
    pub fn with_bonding_curve_progress(mut self, progress: f64) -> Self {
        self.bonding_curve_progress = Some(progress);
        self
    }

    /// Add risk level to metadata
    pub fn with_risk_level(mut self, level: RiskLevel) -> Self {
        self.risk_level = Some(level);
        self
    }

    /// Add token mint to metadata
    pub fn with_token_mint(mut self, mint: Pubkey) -> Self {
        self.token_mint = Some(mint);
        self
    }

    /// Build the SwapPlan
    ///
    /// Returns an error if required fields are missing.
    pub fn build(self) -> anyhow::Result<SwapPlan> {
        let amount_in = self
            .amount_in
            .ok_or_else(|| anyhow::anyhow!("amount_in is required"))?;

        let min_amount_out = self
            .min_amount_out
            .ok_or_else(|| anyhow::anyhow!("min_amount_out is required"))?;

        let timeout = self
            .timeout
            .ok_or_else(|| anyhow::anyhow!("timeout is required"))?;

        let mut plan = SwapPlan::new(
            self.authority,
            self.pool_amm_id,
            amount_in,
            min_amount_out,
            timeout,
        );

        // Add metadata if any metadata fields are set
        if self.oracle_score.is_some()
            || self.strategy.is_some()
            || self.bonding_curve_progress.is_some()
            || self.risk_level.is_some()
            || self.token_mint.is_some()
        {
            use std::time::{SystemTime, UNIX_EPOCH};
            let created_at = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_secs() as i64;

            plan.metadata = Some(SwapPlanMetadata {
                oracle_score: self.oracle_score.unwrap_or(0),
                strategy: self.strategy.unwrap_or_else(|| "unknown".to_string()),
                bonding_curve_progress: self.bonding_curve_progress,
                risk_level: self.risk_level.unwrap_or(RiskLevel::Medium),
                token_mint: self.token_mint.unwrap_or_default(),
                created_at,
            });
        }

        Ok(plan)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_swap_plan_creation() {
        let authority = Pubkey::new_unique();
        let pool = Pubkey::new_unique();

        let plan = SwapPlan::new(authority, pool, 1_000_000, 900_000, 1234567890);

        assert_eq!(plan.authority, authority);
        assert_eq!(plan.pool_amm_id, pool);
        assert_eq!(plan.amount_in, 1_000_000);
        assert_eq!(plan.min_amount_out, 900_000);
        assert_eq!(plan.timeout, 1234567890);
        assert!(plan.metadata.is_none());
    }

    #[test]
    fn test_swap_plan_builder() {
        let authority = Pubkey::new_unique();
        let pool = Pubkey::new_unique();
        let mint = Pubkey::new_unique();

        let plan = SwapPlanBuilder::new(authority, pool)
            .amount_in(1_000_000)
            .min_amount_out(900_000)
            .timeout(1234567890)
            .with_score(85)
            .with_strategy("test_strategy")
            .with_risk_level(RiskLevel::Low)
            .with_token_mint(mint)
            .build()
            .unwrap();

        assert_eq!(plan.amount_in, 1_000_000);
        assert!(plan.metadata.is_some());

        let metadata = plan.metadata.unwrap();
        assert_eq!(metadata.oracle_score, 85);
        assert_eq!(metadata.strategy, "test_strategy");
        assert_eq!(metadata.risk_level, RiskLevel::Low);
        assert_eq!(metadata.token_mint, mint);
    }

    #[test]
    fn test_is_expired() {
        let plan = SwapPlan::new(
            Pubkey::new_unique(),
            Pubkey::new_unique(),
            1_000_000,
            900_000,
            1000,
        );

        assert!(!plan.is_expired(999));
        assert!(!plan.is_expired(1000));
        assert!(plan.is_expired(1001));
    }
}
